on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Build 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: docker build -t zig-wasm-audio-framebuffer .

